### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [dic1911/android_AutoDND#8] opened 2023-04-04 08:05 UTC
As tag 2.1 went away :(

ref: https://gitlab.com/fdroid/fdroiddata/-/commit/c82406c6119d04bc040192209f9c6ab888541d0b

ref: https://web.archive.org/web/20230404080357/https://monitor.f-droid.org/builds/log/moe.dic1911.autodnd/4

/LE: fyi: https://gitlab.com/fdroid/fdroiddata/-/commit/9cb831c034cdabff09ee2740e65e62647fe1b570

**Comment by im030** [comment] 2023-06-01 10:16
Sorry for the inconvenience, I'm working on another update for better detection using Shizuku or root access, will push another update after finished.

**Comment by im030** [comment] 2023-06-14 01:30
I don't know why but it seems this repository gets overwritten over time, I thought I forgot to push and pushed again few days ago, but now the changes are gone again.

Edit: My bad, there's a push hook on my server, will fix later

**Comment by im030** [comment] 2023-06-15 06:30
I think the problem is fixed now, opened a MR on GitLab and got merged earlier today, will close after F-Droid build my update

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13241

**Comment by im030** [comment] 2023-06-19 02:27
Saw them built my update [here](https://monitor.f-droid.org/builds/build), but app page haven't get updated yet
![image](https://github.com/dic1911/android_AutoDND/assets/9561880/39c1ef5e-0cfa-4807-900f-e7dddd6f316a)

**Comment by licaon-kter** [comment] 2023-06-19 03:37
@dic1911 https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by im030** [comment] 2023-06-20 10:48
Closing as update released on F-Droid

**Closed as completed by im030** 2023-06-20 10:48 UTC
